---
purpose: demo

satellite_organization: My_Organization
satellite_location: Tokyo
satellite_admin_username: admin
satellite_activation_key_name: "Demo_Key"
satellite_content_view: "RHEL9_SOE"
satellite_content_view_filter_types:
  - bugfix
  - security
  - enhancement

managed_vms_name_prefix: "managed"
aws_region: ap-northeast-1 # adjust with your preference
wp_weblog_title: "DemoSite"
